### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mai1237** [san-kumar/laravel-crud#1]
Trying to run 
php artisan crud:generate customers.tickets.replies
I get the error below
   Error

  Class "Doctrine\DBAL\Driver\AbstractMySQLDriver" not found

  at C:\xampp\htdocs\abc\abcw\w09\vendor\laravel\framework\src\Illuminate\Database\PDO\MySqlDriver.php:8

Any suggestion

**Comment by san-kumar** [comment]
> Any suggestion

Yes, a few

1. Have you set the mysql password in the .env file?
2. Have you created the db migrations and tables for customer, tickets and replies and run `artisan migration`?
3. Can you please check if laravel can connect to your mysql db

lett me know..

**Comment by san-kumar** [comment]
Okay I found the bug which fixes this. Please run the following command in your project root and update to v1.01

```bash
composer require san-kumar/laravel-crud --dev
```
