### ISSUE TITLE
Generate an initial layout

### ISSUE THREAD

**Issue by gerardp** [san-kumar/laravel-crud#2]
Add the ability to generate an initial layout (dashboard), something similar to this project:
https://github.com/Kamona-WD/kui-laravel-breeze

![1](https://user-images.githubusercontent.com/168353/212667435-ba45cc80-fa78-4f7b-b86d-308fa518e208.PNG)

**Comment by san-kumar** [comment]
There is a layout option using which it is very easy to do this

````bash
$ php artisan crud:generate authors --layout=admin
````
