### ISSUE TITLE
No warning before deleting a record

### ISSUE THREAD

**Issue by rabol** [san-kumar/laravel-crud#7]
Hi

Not sure if this is a bug or a missing feature, but when you delete a record there is no warning before the delete

**Comment by san-kumar** [comment]
I think it's a missing feature. The delete button is hidden a drop-down so I decided not to add a confirmation. It should be easy to do that though. Just open the generate blade file and add the following to the delete link

````html
<a href="..." ... onclick="return confirm('Are you sure?')">Delete</a>
````
